CREATE TABLE "daily_snapshots" (
	"id" serial PRIMARY KEY NOT NULL,
	"date" date NOT NULL,
	"fusion_asof_date" text,
	"fusion_cycle_stage" text,
	"fusion_fragility_color" text,
	"fusion_fragility_label" text,
	"fusion_guidance_label" text,
	"fusion_headline_summary" text,
	"fusion_cycle_tone" text,
	"fusion_narrative_summary" text,
	"fusion_guidance_bullets" jsonb,
	"fusion_watch_commentary" text,
	"gamma_asof_week" text,
	"gamma_cycle_stage_primary" text,
	"gamma_cycle_stage_transition" text,
	"gamma_macro_posture_label" text,
	"gamma_headline_summary" text,
	"gamma_domains" jsonb,
	"gamma_phase_confidence" text,
	"gamma_cycle_tone" text,
	"gamma_overall_summary" text,
	"gamma_domain_details" jsonb,
	"delta_asof_date" text,
	"delta_fragility_color" text,
	"delta_fragility_label" text,
	"delta_fragility_score" integer,
	"delta_template_code" text,
	"delta_template_name" text,
	"delta_pattern_plain" text,
	"delta_posture_code" text,
	"delta_posture_label" text,
	"delta_headline_summary" text,
	"delta_key_drivers" jsonb,
	"delta_next_watch_display" jsonb,
	"delta_phase_used" text,
	"delta_phase_confidence" text,
	"delta_breadth" integer,
	"delta_liquidity" integer,
	"delta_volatility" integer,
	"delta_leadership" integer,
	"delta_breadth_text" text,
	"delta_liquidity_text" text,
	"delta_volatility_text" text,
	"delta_leadership_text" text,
	"delta_rationale_bullets" jsonb,
	"delta_plain_english_summary" text,
	"delta_next_triggers_detail" jsonb,
	"full_analysis" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "daily_snapshots_date_unique" UNIQUE("date")
);
--> statement-breakpoint
CREATE TABLE "status_changes" (
	"id" serial PRIMARY KEY NOT NULL,
	"field_name" text NOT NULL,
	"old_value" text,
	"new_value" text NOT NULL,
	"changed_at" timestamp DEFAULT now() NOT NULL,
	"duration" integer
);
